name: Publish build

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      app_name: Iridia Knowledge Base
      tags: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=sha,format=short
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
